# Generated by Django 3.2.9 on 2021-12-08 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data', models.JSONField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=25)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Key', 'Key'), ('Knife', 'Knife'), ('Pistol', 'Pistol'), ('Rifle', 'Rifle'), ('Shotgun', 'Shotgun'), ('SMG', 'Smg'), ('Sniper Rifle', 'Sniper Rifle'), ('Machinegun', 'Machinegun'), ('Tool', 'Tool'), ('Pass', 'Pass'), ('Container', 'Container'), ('Sticker', 'Sticker'), ('Tag', 'Tag'), ('Kit', 'Kit'), ('Gift', 'Gift'), ('Collectible', 'Collectible'), ('Graffiti', 'Graffiti'), ('Gloves', 'Gloves'), ('Music Kit', 'Music Kit'), ('Agent', 'Agent'), ('Patch', 'Patch')], max_length=100, null=True)),
                ('name', models.CharField(default='', max_length=255)),
                ('market_name', models.CharField(default='', max_length=255)),
                ('market_hash_name', models.CharField(default='', max_length=255)),
                ('lowest_price', models.CharField(default='', max_length=20)),
                ('image_link', models.CharField(default='', max_length=255)),
                ('exterior', models.CharField(max_length=20, null=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='exchanger.inventory')),
                ('slots', models.ManyToManyField(to='exchanger.Slot')),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(default='Rules violation')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
