# Generated by Django 3.2.9 on 2021-12-08 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger', '0002_item_class_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image_link',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
