# Generated by Django 3.2.9 on 2021-12-08 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger', '0003_alter_item_image_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='class_id',
            new_name='item_id',
        ),
    ]
