# Generated by Django 3.2.9 on 2021-12-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger', '0004_rename_class_id_item_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='trade_link',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
